# Generated by Django 3.0.2 on 2020-01-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirateAdventure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('currentRoom', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
    ]
