# Generated by Django 3.0.2 on 2020-01-24 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piratesthree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piratesthree.Items')),
                ('rarity', models.CharField(default='', max_length=50)),
            ],
            bases=('piratesthree.items',),
        ),
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piratesthree.Items')),
            ],
            bases=('piratesthree.items',),
        ),
        migrations.AddField(
            model_name='items',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
