# Generated by Django 3.0.2 on 2020-01-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200126_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='DEFAULT DESCRIPTION', max_length=255, unique=True),
        ),
    ]
