# Generated by Django 3.0.2 on 2020-01-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200126_2034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerItems',
            new_name='UserInfo',
        ),
    ]
