# Generated by Django 3.0.2 on 2020-01-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200126_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='weapons',
            field=models.CharField(default='DEFAULT DESCRIPTION', max_length=255),
        ),
    ]
