# Generated by Django 3.0.2 on 2020-01-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userinfo_weapons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='weapons',
        ),
    ]
