# Generated by Django 3.0.2 on 2020-01-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piratestwo', '0002_itemlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='x',
        ),
        migrations.RemoveField(
            model_name='items',
            name='y',
        ),
    ]
