# Generated by Django 3.0.2 on 2020-01-27 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piratestwo', '0003_auto_20200125_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT ITEM', max_length=255)),
                ('description', models.CharField(default='DEFAULT DESCRIPTION', max_length=255)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='durability',
        ),
        migrations.CreateModel(
            name='MerchantWeapons',
            fields=[
                ('merchant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='piratestwo.Merchant')),
                ('attack_power', models.IntegerField(default=0)),
            ],
            bases=('piratestwo.merchant',),
        ),
    ]
