# Generated by Django 3.0.2 on 2020-01-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piratestwo', '0004_auto_20200127_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='weapons_power',
            field=models.CharField(default='DEFAULT DESCRIPTION', max_length=255),
        ),
    ]
