# Generated by Django 3.0.2 on 2020-01-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piratestwo', '0006_playerweapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='trade',
            field=models.CharField(default='DEFAULT', max_length=255),
        ),
        migrations.AlterField(
            model_name='playerweapons',
            name='description',
            field=models.CharField(default='DEFAULT', max_length=255),
        ),
        migrations.AlterField(
            model_name='playerweapons',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=255),
        ),
        migrations.AlterField(
            model_name='playerweapons',
            name='weapons_power',
            field=models.CharField(default='DEFAULT', max_length=255),
        ),
    ]
